# Generated by Django 4.1.5 on 2023-02-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipsandcracksrepair',
            name='glass_type',
            field=models.CharField(choices=[('front', 'Лобовое'), ('side', 'Боковое'), ('rear', 'Заднее')], max_length=5, verbose_name='Стекло'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='camera_assistant',
            field=models.BooleanField(default=False, verbose_name='камера-ассистент'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='car_body_type',
            field=models.CharField(choices=[('sd', 'Седан'), ('htch', 'Хэтчбэк'), ('un', 'Универсал')], default='sd', max_length=4, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='full_glass_heating',
            field=models.BooleanField(default=False, verbose_name='полный обогрев стекла'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='glass_type',
            field=models.CharField(choices=[('front', 'Лобовое'), ('side', 'Боковое'), ('rear', 'Заднее')], max_length=5, verbose_name='Стекло'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='i_dont_know',
            field=models.BooleanField(default=False, verbose_name='не знаю'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='projection',
            field=models.BooleanField(default=False, verbose_name='проекция'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='rain_sensor',
            field=models.BooleanField(default=False, verbose_name='датчик долждя'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='vin_code_windows',
            field=models.BooleanField(default=False, verbose_name='окошко под VIN'),
        ),
        migrations.AlterField(
            model_name='glassreplace',
            name='wiper_heating',
            field=models.BooleanField(default=False, verbose_name='обогрев зоны дворников'),
        ),
    ]
