# Generated by Django 4.1.5 on 2023-02-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_chipsandcracksrepair_glass_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyglass',
            name='car_body_type',
            field=models.CharField(choices=[('sd', 'Седан'), ('htch', 'Хэтчбэк'), ('un', 'Универсал')], default='sd', max_length=4, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='buyglass',
            name='glass_type',
            field=models.CharField(choices=[('front', 'Лобовое'), ('side', 'Боковое'), ('rear', 'Заднее')], max_length=5, verbose_name='Стекло'),
        ),
        migrations.AlterField(
            model_name='glasstinting',
            name='glass_type',
            field=models.CharField(choices=[('front', 'Лобовое'), ('side', 'Боковое'), ('rear', 'Заднее')], max_length=5, verbose_name='Стекло'),
        ),
        migrations.AlterField(
            model_name='glasstintingphotos',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.glasstinting', verbose_name='Заявка'),
        ),
    ]
