# Generated by Django 4.1.5 on 2023-02-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_buyglass_car_body_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValueStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, verbose_name='ключ')),
                ('value', models.TextField(max_length=2000, verbose_name='ключ')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
                'ordering': ['-id'],
            },
        ),
    ]
