# Generated by Django 4.1.5 on 2023-03-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_tlguser_is_fake_remove_tlguser_is_scam_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUsers',
        ),
    ]
